### ISSUE TITLE
Package Request: Signal Desktop

### ISSUE THREAD

**Issue by Abhinav1217** [area-of-dev/Signal.AppImage#1]
Signal is a secure messaging service similar to telegram or wire. But it is considered more secure than both, and is also completely open source unlike telegram.

Currently they provide source code release only, and debian repo hosted on their own server.

Website: https://signal.org  
Repo: https://github.com/signalapp/Signal-Desktop  
License: AGPL3 with copyrights belonging to a 501c3 nonprofit

**Comment by AlexWoroschilow** [comment]
Page: https://apprepo.de/appimage/signal

**Comment by AlexWoroschilow** [comment]
@Abhinav1217 would you like to try to build the appimage using all the examples available here
https://github.com/area-of-dev
?

**Comment by Abhinav1217** [comment]
>  would you like to try to build the appimage using all the examples available here

Yes. I have been unsuccessfully trying  to learn about appimage packaging since you sparked an interest in me last year (https://github.com/area-of-dev/Pinta.AppImage/issues/1#issuecomment-1030803522) .  

Before asking you for adding signal in your collection, I tried to build one myself using the ms-teams and Olive as starting point, (also tried WPS but without docker, I couldn't make it work last time or this time.)

When I ran the command, docker wanted to install the whole distro !!!! including xserver xwayland  and gnome-shell !!! And that is after installing a lot of stuffs before this. According to my network meter, It had already used 1.2GB of data.  

```
 x11-xserver-utils xauth xdg-dbus-proxy xfonts-base xfonts-encodings
  xfonts-utils xkb-data xml-core xserver-common xserver-xephyr xserver-xorg
  xserver-xorg-core xserver-xorg-input-all xserver-xorg-input-libinput
  xserver-xorg-input-wacom xserver-xorg-legacy xserver-xorg-video-all
  xserver-xorg-video-amdgpu xserver-xorg-video-ati xserver-xorg-video-fbdev
  xserver-xorg-video-intel xserver-xorg-video-nouveau xserver-xorg-video-qxl
  xserver-xorg-video-radeon xserver-xorg-video-vesa xserver-xorg-video-vmware
  xwayland yaru-theme-gnome-shell yelp yelp-xsl zenity zenity-common
0 upgraded, 584 newly installed, 0 to remove and 0 not upgraded.
Need to get 312 MB of archives.
After this operation, 1579 MB of additional disk space will be used.
Get:1 https://updates.signal.org/desktop/apt xenial/main amd64 signal-desktop amd64 6.1.0 [121 MB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 liblocale-gettext-perl amd64 1.07-4 [17.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 keyboard-configuration all 1.194ubuntu3 [190 kB]
Get:`
```

And this is after I used your teams setup to build a teams appimage. I didn't ran `make clean` so I thought things must already be cached.

**Comment by AlexWoroschilow** [comment]
@Abhinav1217 you will find an AppImage here:
https://github.com/area-of-dev/Signal.AppImage/releases
